"""empty message

Revision ID: 5442f4ab2038
Revises: 5808433e767e
Create Date: 2020-09-29 11:09:33.501000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5442f4ab2038'
down_revision = '5808433e767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_timestamp'), 'fish', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_timestamp'), table_name='fish')
    op.drop_table('fish')
    # ### end Alembic commands ###
